#!/usr/bin/env bash

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/default"

#-------------------------- END: Settings --------------------------------

rsync -e "ssh -p 7822" -avz doesborg@doesb.org:/home/doesborg/public_html/veldeke/docroot/sites/default/files $SITEDIR_PATH
#rsync -e "ssh -p 7822" -avz doesborg@doesb.org:/home/doesborg/public_html/svv-project/db ${PROJECT_ROOT}

