#!/usr/bin/env bash

# resets the local dev environment

PROJ_DIR="$HOME/Sites/veldeke"

fin up
git stash clear
git stash
git checkout master
git pull origin master

fin drush sqlq "truncate table cache_update" --root=docroot
fin drush cc drush --root=docroot
fin drush up -y --root=docroot

git add docroot/*
git commit -m "updating core & contrib packages"
git push origin master
